version: '3.8'

services:
  db:
    container_name: db
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/data/db

  node_app:
    container_name: node_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

volumes:
  db_data: {}
