version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: ["npm", "run", "dev"]
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

volumes:
  db_data: {}
